import stylex from "@stylexjs/stylex";

export const metadata = {
  title: "StyleX Demo",
  description: "Generated by create next app with stylex",
};

export default function DemoLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <nav className={stylex(styles.nav)}>
        <a href="/" className={stylex(styles.link)}>
          Demo
        </a>
      </nav>
      {children}
    </section>
  );
}

const styles = stylex.create({
  nav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "60px",
    width: "100%",
    fontSize: "calc(10px + 2vmin)",
    color: "white",
    padding: "0 10px",
    backgroundColor: "#282c34",
    boxShadow: "0 0 5px rgba(0, 0, 0, 0.3)",
  },
  link: {
    color: "inherit",
    textDecoration: "none",
  },
});
